services:
  revived_bot:
    build: .
    volumes:
      - .:/code
    depends_on:
      - revived_redis
    restart: unless-stopped
    networks:
    - default
  revived_redis:
    container_name: revived_redis
    image: redis/redis-stack:latest
    volumes:
      - ./.storage:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped
    networks:
    - default